### PR TITLE
FEAT: ADDED MODIFIER

### PR DESCRIPTION
**Pull request by 0xm00k**

### CODE REVIEW

**Comment by AnandK-2024** [comment]
add modifier in buy function also

**Comment by raiyanmook27** [comment]
Sure will do.

**Comment by raiyanmook27** [comment]
Just realized with the buyNFt function I can't use the modifier, I will have to use the require to make the checks.

**Comment by AnandK-2024** [comment]
@raiyanmook27  you can create one more issue for securing  buynft : make sure Owner of the  nft can't buy own NFTs any how.

**Pull request merged**
